[build]
  base = "efootball-tournament-manager"
  command = "npm run build"
  publish = "efootball-tournament-manager/dist/efootball-tournament-manager/browser"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200